name: Fetch and Record Releases

on:
  schedule:
    # 每天运行一次，你可以根据需要调整频率
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch_releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Releases
        run: python fetch_releases.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update release data" -a || echo "No changes to commit"
          git push