name: Fetch and Record Releases

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch_releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Releases
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          export ACCESS_TOKEN
          python scripts/fetch_releases.py

      - name: Commit and Push
        run: |
          git config --local user.email "freemankevin2017@gmail.com"
          git config --local user.name "FreemanKevin"
          git add .
          git commit -m "Update release data" -a || echo "No changes to commit"
          git push